import { getLocations } from '@/lib/utils';
import { notFound } from 'next/navigation';
import Link from 'next/link';

type Props = {
  params: Promise<{
    state: string;
    city: string;
  }>;
};

export default async function CityPage({ params }: Props) {
  const { state: stateSlug, city: citySlug } = await params;

  // 1. Find the Data manually since we don't have a specific helper for just City yet
  const allData = getLocations();
  const stateData = allData.find((s) => s.slug === stateSlug);
  const cityData = stateData?.cities.find((c) => c.slug === citySlug);

  if (!stateData || !cityData) {
    return notFound();
  }

  return (
    <div className="min-h-screen font-sans text-gray-800">
      {/* --- HEADER --- */}
      <header className="border-b border-gray-200 sticky top-0 bg-white z-50">
        <div className="max-w-7xl mx-auto px-4 py-4 flex justify-between items-center">
          <div className="text-2xl font-bold text-blue-900">Sears <span className="font-light text-blue-600">Home Services</span></div>
          <button className="bg-blue-600 text-white px-6 py-2 rounded font-bold hover:bg-blue-700">
            Schedule Now
          </button>
        </div>
      </header>

      {/* --- HERO SECTION --- */}
      <div className="bg-blue-900 text-white py-16">
        <div className="max-w-7xl mx-auto px-4 text-center">
          <h1 className="text-4xl md:text-5xl font-bold mb-4">
            Appliance Repair & HVAC in {cityData.name}, {stateData.abbr}
          </h1>
          <p className="text-xl text-blue-100 mb-8">{cityData.description}</p>
        </div>
      </div>

      {/* --- BRANCH LIST SECTION --- */}
      <div className="max-w-7xl mx-auto px-4 py-16">
        <h2 className="text-3xl font-bold text-gray-900 mb-8 border-b pb-4">
          Locations in {cityData.name}
        </h2>

        {/* This Grid lists all the branches generated by your Python script */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {cityData.branches.map((branch) => (
            <div key={branch.slug} className="border border-gray-200 rounded-lg p-6 hover:shadow-lg transition-shadow bg-white">
              <h3 className="text-xl font-bold text-blue-900 mb-2">{branch.name}</h3>
              <p className="text-gray-600 mb-1">{branch.address}</p>
              <p className="text-gray-600 mb-4">{cityData.name}, {stateData.abbr} {branch.zip_code}</p>
              
              <div className="flex flex-col gap-3">
                <a href={`tel:${branch.phone}`} className="text-blue-600 font-bold">
                  📞 {branch.phone}
                </a>
                
                {/* This Link takes you to the specific Branch Page we just built */}
                <Link 
                  href={`/locations/${stateData.slug}/${cityData.slug}/sears-appliance-repair/${branch.slug}`}
                  className="block text-center bg-gray-100 hover:bg-gray-200 text-gray-900 py-2 rounded font-medium"
                >
                  View Location Details →
                </Link>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* --- REVIEWS SNAPSHOT (Static for layout) --- */}
      <div className="bg-gray-50 py-16">
        <div className="max-w-7xl mx-auto px-4">
          <h2 className="text-2xl font-bold mb-6">Recent Customer Reviews in {cityData.name}</h2>
          <div className="grid md:grid-cols-2 gap-6">
             <div className="bg-white p-6 rounded shadow">
                <div className="text-yellow-400 text-xl mb-2">★★★★★</div>
                <p className="italic text-gray-600">"The technician was knowledgeable and friendly. Did a great job repairing my washer."</p>
                <p className="text-sm text-gray-400 mt-4">- Verified Customer, {cityData.name}</p>
             </div>
             <div className="bg-white p-6 rounded shadow">
                <div className="text-yellow-400 text-xl mb-2">★★★★★</div>
                <p className="italic text-gray-600">"Very dependable and honest! I will use Sears Appliance Repair again if needed."</p>
                <p className="text-sm text-gray-400 mt-4">- Verified Customer, {cityData.name}</p>
             </div>
          </div>
        </div>
      </div>

    </div>
  );
}